export { fetchData } from './fetch/fetch-data'
export { formatDataFromArray } from './formatters/format-data-from-array'
export { formatFilmModel } from './formatters/format-film-model'
export { formatCharacterModel } from './formatters/format-character-model'
export { sortArray } from './sorters/sort-array'
export { filterArrayByName } from './filters/filter-array-by-name'
