export { getFilmModel } from './get-film-model'
export { getItemModel } from './get-item-model'
export { getPeopleModel } from './get-people-model'
export { getPlanetModel } from './get-planet-model'
export { getSpecyModel } from './get-specy-model'
export { getStarshipModel } from './get-starship-model'
export { getVehicleModel } from './get-vehicle-model'
